# Generated by Django 2.0.1 on 2018-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180403_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.BooleanField(default=0, verbose_name='サムネイル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank='True', null='True', upload_to='images/'),
        ),
    ]
