# Generated by Django 2.0.1 on 2018-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180404_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(verbose_name='サムネイル'),
        ),
    ]
