# Generated by Django 2.0.1 on 2018-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default='', verbose_name='サムネイル'),
        ),
    ]
