# Generated by Django 2.0.4 on 2018-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180404_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, default='', help_text='メディアフォルダから選び「uploads/2018/04/03/readingdog.jpg」のように入力', max_length=255, null=True, verbose_name='サムネイル'),
        ),
    ]
